CREATE TABLE Concert (
    ConcertID INT IDENTITY(1,1) NOT NULL,
    OrganizerUserID INT NULL,
    ArtistID INT NULL,
    VenueID INT NULL,
    ConcertName NVARCHAR(255) NOT NULL,
    StartDatetime DATETIME2(7) NULL,
    EndDatetime DATETIME2(7) NULL,
    ConcertStatus VARCHAR(32) NOT NULL,
    SaleStartDatetime DATETIME2(7),
    SaleEndDatetime DATETIME2(7),
    PurchaseLimit INT NOT NULL,
    TemporaryHoldDuration INT,
    FairAccessEnabled BIT NOT NULL,
    WaitlistEnabled BIT NOT NULL,
    SalesPaused BIT NOT NULL,
    CancellationPolicy NVARCHAR(500),
    RefundPolicy NVARCHAR(500),
    CancellationDeadlineHours INT,
    RefundPercentage DECIMAL(5,2),
    IsDeleted BIT NOT NULL DEFAULT 0,
    CONSTRAINT PK_Concert PRIMARY KEY CLUSTERED (ConcertID),
    CONSTRAINT FK_Concert_Organizer FOREIGN KEY (OrganizerUserID) REFERENCES UserAccount(UserID),
    CONSTRAINT FK_Concert_Artist FOREIGN KEY (ArtistID) REFERENCES Artist(ArtistID),
    CONSTRAINT FK_Concert_Venue FOREIGN KEY (VenueID) REFERENCES Venue(VenueID),
    CONSTRAINT CHK_Concert_Status CHECK (ConcertStatus IN ('Draft', 'Published', 'OnSale', 'SaleClosed', 'Completed', 'Cancelled')),
    CONSTRAINT CHK_Concert_Dates CHECK (EndDatetime IS NULL OR StartDatetime IS NULL OR EndDatetime > StartDatetime),
    CONSTRAINT CHK_Concert_SaleDates CHECK (SaleEndDatetime >= SaleStartDatetime),
    -- Phong thu: PurchaseLimit phai > 0 (BR20); TemporaryHoldDuration neu co phai > 0
    CONSTRAINT CHK_Concert_PurchaseLimit CHECK (PurchaseLimit > 0),
    CONSTRAINT CHK_Concert_HoldDuration CHECK (TemporaryHoldDuration IS NULL OR TemporaryHoldDuration > 0)
);
