CREATE TABLE Concert (
    ConcertID INT IDENTITY(1,1) NOT NULL,
    OrganizerUserID INT NOT NULL,
    ArtistID INT NOT NULL,
    VenueID INT NOT NULL,
    ConcertName NVARCHAR(255) NOT NULL,
    StartDatetime DATETIME2(7) NOT NULL,
    EndDatetime DATETIME2(7) NOT NULL,
    ConcertStatus VARCHAR(32) NOT NULL,
    SaleStartDatetime DATETIME2(7),
    SaleEndDatetime DATETIME2(7),
    PurchaseLimit INT NOT NULL,
    TemporaryHoldDuration INT,
    FairAccessEnabled BIT NOT NULL,
    WaitlistEnabled BIT NOT NULL,
    SalesPaused BIT NOT NULL,
    CancellationPolicy NVARCHAR(500),
    RefundPolicy NVARCHAR(500),
    CONSTRAINT PK_Concert PRIMARY KEY CLUSTERED (ConcertID),
    CONSTRAINT FK_Concert_Organizer FOREIGN KEY (OrganizerUserID) REFERENCES UserAccount(UserID),
    CONSTRAINT FK_Concert_Artist FOREIGN KEY (ArtistID) REFERENCES Artist(ArtistID),
    CONSTRAINT FK_Concert_Venue FOREIGN KEY (VenueID) REFERENCES Venue(VenueID),
    CONSTRAINT CHK_Concert_Status CHECK (ConcertStatus IN ('Draft', 'Published', 'OnSale', 'SaleClosed', 'Completed', 'Cancelled')),
    CONSTRAINT CHK_Concert_Dates CHECK (EndDatetime > StartDatetime),
    CONSTRAINT CHK_Concert_SaleDates CHECK (SaleEndDatetime >= SaleStartDatetime)
);
