CREATE TABLE Seat (
    SeatID INT IDENTITY(1,1) NOT NULL,
    ZoneID INT NOT NULL,
    VenueID INT NOT NULL,
    SeatCode VARCHAR(64) NOT NULL,
    SeatLabel NVARCHAR(255),
    CONSTRAINT PK_Seat PRIMARY KEY CLUSTERED (SeatID),
    CONSTRAINT FK_Seat_Zone FOREIGN KEY (ZoneID) REFERENCES Zone(ZoneID),
    CONSTRAINT FK_Seat_Venue FOREIGN KEY (VenueID) REFERENCES Venue(VenueID),
    CONSTRAINT UQ_Seat_Venue_SeatCode UNIQUE (VenueID, SeatCode)
);
